#!/usr/bin/python
#
# Copyright (c) 2016 Maciej Borzecki
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import requests
import argparse
import logging
import os
import json
from six.moves import configparser


def parse_arguments():
    parser = argparse.ArgumentParser(description='Slack Sender')
    parser.add_argument('-u', '--webhook-url', default=None,
                        help='Slack webhook URL')
    parser.add_argument('-a', '--send-as', default=None,
                        help='Send as')
    parser.add_argument('-t', '--to', help='Send to #channel, @user')
    parser.add_argument('message', help='Message')
    return parser.parse_args()


def main(opts):
    url = os.environ.get('SLACK_WEBHOOK_URL', None)

    if not url:
        url = opts.webhook_url

    user_conf = os.path.expanduser('~/.config/slack-send/config')
    if os.path.exists(user_conf):
        conf = configparser.ConfigParser()
        conf.read(user_conf)

        try:
            if not url and conf.has_option('slack', 'webhook_url'):
                url = conf.get('slack', 'webhook_url')

            if not opts.send_as and conf.has_option('slack', 'send_as'):
                opts.send_as = conf.get('slack', 'send_as')

            if not opts.to and conf.has_option('slack', 'default_to'):
                opts.to = conf.get('slack', 'default_to')
        except KeyError:
            pass

    if not url:
        logging.error('Error: no webhook URL provided')
        logging.error('Either use -u or set SLACK_WEBHOOK_URL')
        raise SystemExit(1)

    if not opts.to:
        logging.erro('Cannot send a message with no destination')
        raise SystemExit(1)

    if not opts.send_as:
        opts.send_as = 'bot'

    payload = {
        'channel': opts.to,
        'text': opts.message
    }

    if opts.send_as:
        payload['username'] = opts.send_as

    logging.debug('sending message to %s', opts.to)
    logging.debug('message: %s', json.dumps(payload))

    r = requests.post(url, data=json.dumps(payload))

    logging.debug('status: %d', r.status_code)
    logging.debug('response: %s', r.text)


if __name__ == '__main__':
    opts = parse_arguments()

    logging.basicConfig(level=logging.DEBUG)

    main(opts)

