#!/bin/sh


while true; do
    case $1 in
        -a)
            as="-a $2"
            shift 2
            ;;
        -t)
            to="--to $2"
            shift 2
            ;;
        -h|--help)
            echo "Usage:"
            echo "$(basename $0) [-a <as>] [-t <to>] [--] <commands..>"
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *)
            break
            ;;
    esac
done

eval $*

ssend $as $to "Command \`$*\` finished with status $? on host $(hostname)"
